### ISSUE TITLE
Unknown option -z with Inkscape 1.0

### ISSUE THREAD

**Issue by yochananmarqos** [varlesh/material-cursors#2]
Manjaro Linux
GNOME 3.36.2
`inkscape` 1.0-2

```
bash build.sh
=> Workon './src/material_cursors' ...
Unknown option -z
*** ^ repeated many times ***
make: *** [Makefile:7: build] Error 123
```

**Comment by varlesh** [comment]
it's not tested with inkscape 1.0. We build with 0.92 version.
try change option `-z` to `--without-gui` on **build.sh**

**Comment by yochananmarqos** [comment]
I replaced `-z` with `--without-gui` and now see `Unknown option --without-gui` instead.

**Comment by varlesh** [comment]
see man or help for this option or downgrade to 092, it's available on aur. Builded version alredy available on Pling Store.

**Comment by varlesh** [comment]
https://aur.archlinux.org/packages/inkscape-092-git/

**Comment by yochananmarqos** [comment]
It turns out no GUI is the default and now there's `g, --with-gui` to enable it instead. 

`-e, --export-png=FILENAME` is now `-o, --export-filename=FILENAME`.

I fixed the build by replacing `-z -e` with `-o`.

**Comment by francoism90** [comment]
@varlesh Is this going to be built against Inkscape 1.0 soon? If not, I'll add the patch @yochananmarqos provided.

**Comment by SmartFinn** [comment]
@francoism90 I'll add Inkscape 1.0 support in build.sh asap.

**Comment by SmartFinn** [comment]
Inkscape 1.0 support was added.

**Comment by yochananmarqos** [comment]
@SmartFinn Could you also add it for the other cursor sets?

**Comment by SmartFinn** [comment]
@varlesh
