### ISSUE TITLE
Add a thumbnail image

### ISSUE THREAD

**Issue by ghost** [varlesh/material-cursors#4]
Can you add a thumbnail image like the DMZ cursors?
![zx](https://user-images.githubusercontent.com/109312533/184759588-dd1be669-c366-4826-b82e-598e4e2836ab.png)
![zc](https://user-images.githubusercontent.com/109312533/184759599-44a0453f-27a2-4b70-a093-f8a958a0ed14.png)

I also take this opportunity to thank you for this cursor, I love it a lot <3

**Comment by varlesh** [comment]
What DE you use? On  KDE fine rendered thumbnail:
![image](https://user-images.githubusercontent.com/8083855/184787297-284805f7-f9ca-403d-b830-503a11cfd1a2.png)

**Comment by ghost** [comment]
I use Cinnamon 5.4.10 (Linux Mint 21).

**Comment by ghost** [comment]
Also DMZ Cursors folder have an extra file `cursor.theme`
![x](https://user-images.githubusercontent.com/109312533/184788594-408cca05-85d4-403a-929a-5caecac43670.png)
![c](https://user-images.githubusercontent.com/109312533/184788600-051dab51-c767-415f-93f2-80ce62cdc655.png)

**Comment by varlesh** [comment]
hm, strange on sources not have cursor.theme:
https://github.com/ganwell/dmz-cursors/releases
Thanks for the request, I'm investigating this issue on near future.

**Comment by varlesh** [comment]
Also i'm found some symlinks:
![image](https://user-images.githubusercontent.com/8083855/184790205-54cd780c-ed78-405b-94b0-810c0db5ba50.png)
Especially the **icon** file, perhaps it is a thumbnail

**Comment by ghost** [comment]
That's great! :D Thanks for your time, I hope you have a solution. <3

**Comment by varlesh** [comment]
Please test it:
[material_cursors.zip](https://github.com/varlesh/material-cursors/files/9356317/material_cursors.zip)

**Comment by ghost** [comment]
It worked! Thanks! <3
![mouse](https://user-images.githubusercontent.com/109312533/185198313-ec4b3307-ec4a-4f5a-9274-3efd1755a96d.png)
