### ISSUE TITLE
Better way to download releases

### ISSUE THREAD

**Issue by leath-dub** [varlesh/material-cursors#7]
I have no issues using an external site to download releases, however specifically pling does not seem to allow you to get a download link. I would love to be able to use curl to pull releases and its not possible afaik with pling.

Also would love to here if I am wrong and missed something :).

**Comment by varlesh** [comment]
You can clone repo and make it. I'm not seen problem

**Comment by leath-dub** [comment]
> You can clone repo and make it. I'm not seen problem

well yes of course, but them I need to pull all the dependencies too.

**Comment by varlesh** [comment]
Should I give you a magic button or what?

> > You can clone repo and make it. I'm not seen problem
> 
> well yes of course, but them I need to pull all the dependencies too.
If you do not have access, it is obvious that the problem is not on our side.

**Comment by leath-dub** [comment]
> Should I give you a magic button or what?
> 
> > > You can clone repo and make it. I'm not seen problem
> > 
> > 
> > well yes of course, but them I need to pull all the dependencies too.
> > If you do not have access, it is obvious that the problem is not on our side.

no I am simply pointing out that the only way to access the binary release is manually, i.e. you cant just curl a link

have nothing against the platform

**Comment by varlesh** [comment]
> no I am simply pointing out that the only way to access the binary release is manually, i.e. you cant just curl a link

Do you want the truth? Good! Pling is the only platform that donates to us, that's all!
The sources are open, the build rules are written... What else do you need?

**Comment by leath-dub** [comment]
> > no I am simply pointing out that the only way to access the binary release is manually, i.e. you cant just curl a link
> 
> Do you want the truth? Good! Pling is the only platform that donates to us, that's all! The sources are open, the build rules are written... What else do you need?

I mean dont take my query the wrong way. I was kinda wondering if anyone knew how to get a direct dl link from pling

**Comment by varlesh** [comment]
> I mean dont take my query the wrong way. I was kinda wondering if anyone knew how to get a direct dl link from pling


What does this have to do with us?

**Comment by leath-dub** [comment]
everything, thats the platform you use to release binaries
